"""empty message

Revision ID: 0178050de211
Revises: 7a023ed63fe8
Create Date: 2023-06-05 22:52:22.618314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0178050de211'
down_revision = '7a023ed63fe8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('is_paid', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'is_paid')
    # ### end Alembic commands ###
