"""empty message

Revision ID: 12f4ba6b7e7c
Revises: c41b973cdba4
Create Date: 2023-06-05 22:09:40.728446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12f4ba6b7e7c'
down_revision = 'c41b973cdba4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
