"""empty message

Revision ID: 139a5fc8b7ea
Revises: fd9b82102ec7
Create Date: 2023-06-05 13:36:04.675858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '139a5fc8b7ea'
down_revision = 'fd9b82102ec7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
