"""empty message

Revision ID: 1417c9565e67
Revises: 99dfcc2640d0
Create Date: 2023-06-02 00:07:48.368198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1417c9565e67'
down_revision = '99dfcc2640d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('populate', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foods', 'populate')
    # ### end Alembic commands ###
