"""empty message

Revision ID: 3d4c9d3fad83
Revises: 4246de43856f
Create Date: 2023-06-01 12:11:13.371634

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d4c9d3fad83'
down_revision = '4246de43856f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('menu', sa.String(length=255), nullable=False))
    op.add_column('orders', sa.Column('call', sa.Boolean(), nullable=False))
    op.add_column('orders', sa.Column('content', sa.String(length=255), nullable=True))
    op.alter_column('orders', 'table_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint('orders_ibfk_1', 'orders', type_='foreignkey')
    op.drop_column('orders', 'food_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('food_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('orders_ibfk_1', 'orders', 'foods', ['food_id'], ['id'])
    op.alter_column('orders', 'table_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('orders', 'content')
    op.drop_column('orders', 'call')
    op.drop_column('orders', 'menu')
    # ### end Alembic commands ###
