"""empty message

Revision ID: 4b694ce29c87
Revises: 139a5fc8b7ea
Create Date: 2023-06-05 14:02:06.066694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b694ce29c87'
down_revision = '139a5fc8b7ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
