"""empty message

Revision ID: 609d1e6a85b2
Revises: 3d4c9d3fad83
Create Date: 2023-06-01 18:59:39.624892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '609d1e6a85b2'
down_revision = '3d4c9d3fad83'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_ibfk_2', 'orders', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('orders_ibfk_2', 'orders', 'tables', ['table_id'], ['id'])
    # ### end Alembic commands ###
