"""empty message

Revision ID: 7a023ed63fe8
Revises: becda9954814
Create Date: 2023-06-05 22:51:38.436395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a023ed63fe8'
down_revision = 'becda9954814'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
