"""empty message

Revision ID: 817b1eff17f0
Revises: 3aee95c69416
Create Date: 2023-05-31 15:41:18.608146

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '817b1eff17f0'
down_revision = '3aee95c69416'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reciepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_name', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reciepts_id'), 'reciepts', ['id'], unique=False)
    op.drop_index('ix_ingredients_id', table_name='ingredients')
    op.drop_table('ingredients')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('food_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('amount', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_ingredients_id', 'ingredients', ['id'], unique=False)
    op.drop_index(op.f('ix_reciepts_id'), table_name='reciepts')
    op.drop_table('reciepts')
    # ### end Alembic commands ###
