"""empty message

Revision ID: 83ce1e3b0a64
Revises: 609d1e6a85b2
Create Date: 2023-06-01 19:01:58.328742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83ce1e3b0a64'
down_revision = '609d1e6a85b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
