"""empty message

Revision ID: 99dfcc2640d0
Revises: c97103af1192
Create Date: 2023-06-01 20:37:41.036170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99dfcc2640d0'
down_revision = 'c97103af1192'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
