"""empty message

Revision ID: aa4af546c151
Revises: ccaf592578c6
Create Date: 2023-06-02 00:44:59.074013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa4af546c151'
down_revision = 'ccaf592578c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('is_paid', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'is_paid')
    # ### end Alembic commands ###
