"""empty message

Revision ID: becda9954814
Revises: 12f4ba6b7e7c
Create Date: 2023-06-05 22:25:07.182327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'becda9954814'
down_revision = '12f4ba6b7e7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
