"""empty message

Revision ID: c41b973cdba4
Revises: fb2092a0f401
Create Date: 2023-06-05 21:56:50.732438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c41b973cdba4'
down_revision = 'fb2092a0f401'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('table_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'table_time')
    # ### end Alembic commands ###
