"""empty message

Revision ID: c97103af1192
Revises: 83ce1e3b0a64
Create Date: 2023-06-01 19:02:31.439544

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c97103af1192'
down_revision = '83ce1e3b0a64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('price', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
