"""empty message

Revision ID: ccaf592578c6
Revises: 1417c9565e67
Create Date: 2023-06-02 00:42:42.819433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccaf592578c6'
down_revision = '1417c9565e67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('pick', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foods', 'pick')
    # ### end Alembic commands ###
