"""empty message

Revision ID: d41d1a5e21aa
Revises: fb7a2c60b8f9
Create Date: 2023-06-06 16:40:15.158139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd41d1a5e21aa'
down_revision = 'fb7a2c60b8f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
