"""empty message

Revision ID: fb2092a0f401
Revises: 4b694ce29c87
Create Date: 2023-06-05 20:03:58.225224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb2092a0f401'
down_revision = '4b694ce29c87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'order_time')
    # ### end Alembic commands ###
