"""empty message

Revision ID: fd9b82102ec7
Revises: 86c391ade161
Create Date: 2023-06-05 00:09:49.621177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd9b82102ec7'
down_revision = '86c391ade161'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
