IP = "3.216.219.9"
SERVER_PORT = 5000
MYSQL_PORT = 3306
INF_PORT = 8086

MYSQL_ADMIN_ID = "admin"
MYSQL_ADMIN_PW = "admin"
INF_ADMIN_ID = "admin"
INF_ADMIN_PW = "admin"

MYSQL_DB_NAME = "userinfo"
MYSQL_TABLE_NAME = "data"
INF_DB_NAME = "userinfo"
INF_MEASUREMENT = "data"